In [1]:
# Core libraries
import pandas as pd
import sqlite3
import json

# Display settings (optional but useful)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

print("Environment ready ✅")

Environment ready ✅

In [3]:
import os

os.listdir()

['.anaconda',
 '.conda',
 '.condarc',
 '.continuum',
 '.gradle',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.ms-ad',
 '.redhat',
 '.spyder-py3',
 '.virtual_documents',
 '.vscode',
 '05_11_2025_EDA.ipynb',
 '06_11_2025_EDA.ipynb',
 '06_11_2025_re.ipynb',
 '07_11_2025_re.ipynb',
 '08_11_2025_WebScraping.ipynb',
 '10_11_2025_WebScraping.ipynb',
 '14_10_2025_numpy.ipynb',
 '15_10_2025_numpy.ipynb',
 '16_10_2025_numpy.ipynb',
 '17_10_2025_numpy.ipynb',
 '22_10_2025_Pandas.ipynb',
 '23_10_2025_Pandas.ipynb',
 '24_10_2025_pandas.ipynb',
 '27_10_2025_Pandas.ipynb',
 '28_10_2025_Pandas.ipynb',
 '29_10_2025_pandas.ipynb',
 '30_10_2025_pandas.ipynb',
 '31_10_2025_EDA.ipynb',
 '3D Objects',
 'anaconda3',
 'anaconda_projects',
 'AppData',
 'Application Data',
 'assignment3(For Advance(EDA)).zip',
 'City_Server.xlsx',
 'City_Servey.csv',
 'conditional 438.ipynb',
 'Contacts',
 'Cookies',
 'daily_task_01.ipynb',
 'daily_task_02.ipynb',
 'daily_task_02.zip',
 'daily_task_03.ipynb',
 'daily_task_04.ipynb',
 'daily_task_04.zip',
 'daily_task_05.ipynb',
 'daily_task_05.zip',
 'daily_task_06.ipynb',
 'daily_task_06.zip',
 'daily_task_07.ipynb',
 'daily_task_07.zip',
 'daily_task_08.ipynb',
 'daily_task_08.zip',
 'daily_task_09_while_loops.ipynb',
 'daily_task_09_while_loops.zip',
 'daily_task_1.zip',
 'daily_task_10_str_cond.ipynb',
 'daily_task_10_str_cond.zip',
 'daily_task_11_for_loop.ipynb',
 'daily_task_11_for_loop.zip',
 'daily_task_12_nested_for_loop.ipynb',
 'daily_task_12_nested_for_loop.zip',
 'daily_task_13_comprehensions.ipynb',
 'daily_task_13_comprehensions.zip',
 'daily_task_14_functions.ipynb',
 'daily_task_14_functions.zip',
 'daily_task_15_inheritance.ipynb',
 'daily_task_15_inheritance.zip',
 'daily_task_16_numpy.ipynb',
 'daily_task_16_numpy.zip',
 'daily_task_17_numpy_methods.ipynb',
 'daily_task_17_numpy_methods.zip',
 'daily_task_18_pd.Series.ipynb',
 'daily_task_18_pd.Series.zip',
 'daily_task_19_pandas_DataFrames.ipynb',
 'daily_task_19_pandas_DataFrames.zip',
 'daily_task_20_missing_values.ipynb',
 'daily_task_20_missing_values.zip',
 'daily_task_21_time_series.ipynb',
 'daily_task_21_time_series.zip',
 'daily_task_22_group_by.ipynb',
 'daily_task_22_group_by.zip',
 'daily_task_23_pivot_table.ipynb',
 'daily_task_23_pivot_table.zip',
 'daily_task_24_measures_of_tendency.ipynb',
 'daily_task_24_measures_of_tendency.zip',
 'daily_task_25_Data_Visualization_correct.ipynb',
 'daily_task_25_Data_Visualization_correct.zip',
 'daily_task_3.zip',
 'Documents',
 'Downloads',
 'employees.csv',
 'Favorites',
 'filehandling 438.ipynb',
 'functions 438.ipynb',
 'GROCERY_STORE_ERD.png',
 'GROCERY_STORE_PROJECT.sql',
 'IdeaProjects',
 'ino1.sql',
 'ino2.sql',
 'ino3.sql',
 'ino_3.txt',
 'ino_4.txt',
 'ino_5.txt',
 'ino_EDA_01.ipynb',
 'ino_EDA_02.ipynb',
 'ino_EDA_03.ipynb',
 'ino_numpy_01.ipynb',
 'ino_numpy_02.ipynb',
 'ino_numpy_03.ipynb',
 'ino_numpy_04.ipynb',
 'ino_numpy_05.ipynb',
 'ino_pandas_01.ipynb',
 'ino_pandas_02.ipynb',
 'ino_pandas_03.ipynb',
 'ino_pandas_04.ipynb',
 'ino_pandas_05.ipynb',
 'ino_pandas_06.ipynb',
 'ino_pandas_07.ipynb',
 'ino_RE_01.ipynb',
 'ino_RE_02.ipynb',
 'ino_WebScraping.ipynb',
 'IntelGraphicsProfiles',
 'INTERSHIP.ipynb',
 'Iris.csv',
 'Items.jpeg',
 'ItemScatter.jpeg',
 'Laptop data.csv',
 'LAPTOP_DATA.csv',
 'LAPTOP_DATA1.csv',
 'LibraryDataBaseAnalysis.zip',
 'LibraryManagementSystem.sql',
 'LibraryManagementSystemERD.png',
 'LibraryManagementSystemERDPdf.pdf',
 'Links',
 'loandata.csv',
 'loandata1.csv',
 'loandata2.csv',
 'Local Settings',
 'loops 438.ipynb',
 'missing.csv',
 'MOBILE_DATA.csv',
 'Music',
 'My Documents',
 'mysql_assignment01.sql',
 'mysql_assignment01.zip',
 'mysql_assignment02.sql',
 'mysql_assignment02.zip',
 'mysql_assignment03.sql',
 'mysql_assignment03.zip',
 'mysql_assignment04.sql',
 'mysql_assignment04.zip',
 'mysql_assignment05.sql',
 'mysql_assignment05.zip',
 'mysql_capstone_assignment01.sql',
 'mysql_capstone_assignment01.zip',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{ff1242f2-7d50-11ef-8472-b052160b4a6e}.TM.blf',
 'NTUSER.DAT{ff1242f2-7d50-11ef-8472-b052160b4a6e}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{ff1242f2-7d50-11ef-8472-b052160b4a6e}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'Numpy_10_10_2025.ipynb',
 'numpy_Utube_cdingwitSagar.ipynb',
 'nyc_weather.csv',
 'OneDrive',
 'oops438.ipynb',
 'orders.csv',
 'output.csv',
 'output.json',
 'output.xlsx',
 'pandas_practice.ipynb',
 'pandas_Utube_cdingwitSagar.ipynb',
 'playstore_data.db',
 'Play_store_and_User_reviews_set_1.xlsx',
 'Play_Store_set_2_data_1.json',
 'Play_Store_set_2_data_2.json',
 'PrintHood',
 'programming_task_1(basic_python).ipynb',
 'programming_task_1(basic_python).zip',
 'programming_task_1(for_advanced_python).ipynb',
 'programming_task_1(for_advanced_python).zip',
 'programming_task_2(For Advance(EDA)).ipynb',
 'programming_task_2(For Advance(EDA)).zip',
 'programming_task_3(For Advance(EDA) Python Programmers)-checkpoint.zip',
 'programming_task_3(For Advance(EDA) Python Programmers).ipynb',
 'Recent',
 'REGEX_texT.txt',
 'restaurants.sql',
 'sakila ERD.png',
 'Sales_Data.csv',
 'sales_data_sample.csv',
 'SampleSuperstore.xlsx',
 'sample_Data.json',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'swiggy.csv',
 'Templates',
 'Titanic.csv',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Untitled6.ipynb',
 'userData.csv',
 'userData.txt',
 'userData.xlsx',
 'users.json',
 'user_Data.csv',
 'user_Data.xlsx',
 'Use_reviews_set_2_data.json',
 'Videos',
 'WPS Cloud Files',
 'xenderpc',
 'Z.INO_INTERSHIP',
 'Z.ino_py_folder',
 'Z.powerbi',
 '__pycache__']

In [4]:
orders = pd.read_csv("orders.csv")

orders.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name
0,1,2508,450,18-02-2023,842.97,New Foods Chinese
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian

In [5]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         10000 non-null  int64
 1   user_id          10000 non-null  int64
 2   restaurant_id    10000 non-null  int64
 3   order_date       10000 non-null  object
 4   total_amount     10000 non-null  float64
 5   restaurant_name  10000 non-null  object
dtypes: float64(1), int64(3), object(2)
memory usage: 468.9+ KB

In [6]:
users = pd.read_json("users.json")

users.head()

   user_id    name       city membership
0        1  User_1    Chennai    Regular
1        2  User_2       Pune       Gold
2        3  User_3  Bangalore       Gold
3        4  User_4  Bangalore    Regular
4        5  User_5       Pune       Gold

In [7]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     3000 non-null   int64
 1   name        3000 non-null   object
 2   city        3000 non-null   object
 3   membership  3000 non-null   object
dtypes: int64(1), object(3)
memory usage: 93.9+ KB

In [8]:
# Create SQLite database in memory
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

# Read SQL file
with open("restaurants.sql", "r") as file:
    sql_script = file.read()

# Execute SQL script
cursor.executescript(sql_script)

print("SQL executed successfully ✅")

SQL executed successfully ✅

In [9]:
restaurants = pd.read_sql("SELECT * FROM restaurants", conn)
restaurants.head()

   restaurant_id restaurant_name  cuisine  rating
0              1    Restaurant_1  Chinese     4.8
1              2    Restaurant_2   Indian     4.1
2              3    Restaurant_3  Mexican     4.3
3              4    Restaurant_4  Chinese     4.1
4              5    Restaurant_5  Chinese     4.8

In [10]:
restaurants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   restaurant_id    500 non-null    int64
 1   restaurant_name  500 non-null    object
 2   cuisine          500 non-null    object
 3   rating           500 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 15.8+ KB

In [11]:
orders['user_id'].isna().sum(), orders['restaurant_id'].isna().sum()

(np.int64(0), np.int64(0))

In [12]:
users['user_id'].duplicated().sum()
restaurants['restaurant_id'].duplicated().sum()

np.int64(0)

In [13]:
orders_users = orders.merge(
    users,
    on="user_id",
    how="left"
)

In [14]:
final_df = orders_users.merge(
    restaurants,
    on="restaurant_id",
    how="left"
)

In [15]:
final_df.shape
orders.shape

(10000, 6)

In [16]:
final_df.columns

Index(['order_id', 'user_id', 'restaurant_id', 'order_date', 'total_amount',
       'restaurant_name_x', 'name', 'city', 'membership', 'restaurant_name_y',
       'cuisine', 'rating'],
      dtype='object')

In [17]:
final_df.to_csv("final_food_delivery_dataset.csv", index=False)

print("Final dataset created 🎉")

Final dataset created 🎉

In [18]:
final_df[final_df['membership'] == 'Gold'] \
    .groupby('city')['total_amount'] \
    .sum() \
    .sort_values(ascending=False)

city
Chennai      1080909.79
Pune         1003012.32
Bangalore     994702.59
Hyderabad     896740.19
Name: total_amount, dtype: float64

In [19]:
final_df.groupby('cuisine')['total_amount'] \
    .mean() \
    .sort_values(ascending=False)

cuisine
Mexican    808.021344
Italian    799.448578
Indian     798.466011
Chinese    798.389020
Name: total_amount, dtype: float64

In [20]:
high_value_users = (
    final_df.groupby('user_id')['total_amount']
    .sum()
    .reset_index()
)

high_value_users[high_value_users['total_amount'] > 1000]['user_id'].nunique()

2544

In [21]:
bins = [3.0, 3.5, 4.0, 4.5, 5.0]
labels = ['3.0–3.5','3.6–4.0','4.1–4.5','4.6–5.0']

final_df['rating_range'] = pd.cut(final_df['rating'], bins=bins, labels=labels)

final_df.groupby('rating_range')['total_amount'] \
    .sum() \
    .sort_values(ascending=False)

C:\Users\saisa\AppData\Local\Temp\ipykernel_18352\2317965142.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  final_df.groupby('rating_range')['total_amount'] \

rating_range
4.6–5.0    2197030.75
4.1–4.5    1960326.26
3.0–3.5    1881754.57
3.6–4.0    1717494.41
Name: total_amount, dtype: float64

In [22]:
final_df[final_df['membership'] == 'Gold'] \
    .groupby('city')['total_amount'] \
    .mean() \
    .sort_values(ascending=False)

city
Chennai      808.459080
Hyderabad    806.421034
Bangalore    793.223756
Pune         781.162243
Name: total_amount, dtype: float64

In [23]:
restaurant_counts = final_df.groupby('cuisine')['restaurant_id'].nunique()

In [24]:
revenue_by_cuisine = final_df.groupby('cuisine')['total_amount'].sum()

In [26]:
pd.concat(
    [restaurant_counts, revenue_by_cuisine],
    axis=1,
    keys=['restaurant_count', 'total_revenue']
).sort_values('restaurant_count')

         restaurant_count  total_revenue
cuisine
Chinese               120     1930504.65
Indian                126     1971412.58
Italian               126     2024203.80
Mexican               128     2085503.09

In [27]:
gold_orders = final_df[final_df['membership'] == 'Gold']['order_id'].nunique()
total_orders = final_df['order_id'].nunique()

round((gold_orders / total_orders) * 100)

50

In [30]:
restaurant_stats = (
    final_df.groupby('restaurant_name_x')
    .agg(
        avg_order_value=('total_amount', 'mean'),
        order_count=('order_id', 'count')
    )
    .reset_index()
)

restaurant_stats[
    restaurant_stats['order_count'] < 20
].sort_values('avg_order_value', ascending=False)

                     restaurant_name_x  avg_order_value  order_count
173           Hotel Dhaba Multicuisine      1040.222308           13
354                   Sri Mess Punjabi      1029.180833           12
236              Ruchi Biryani Punjabi      1002.140625           16
343              Sri Delights Pure Veg       989.467222           18
88   Classic Kitchen Family Restaurant       973.167895           19
..                                 ...              ...          ...
64           Annapurna Tiffins Punjabi       621.828947           19
126             Darbar Tiffins Non-Veg       596.815556           18
122          Darbar Restaurant Punjabi       589.972857           14
333             Spice Tiffins Pure Veg       578.578667           15
263                 Ruchi Mess Punjabi       572.686471           17

[170 rows x 3 columns]

In [31]:
final_df.groupby(['membership', 'cuisine'])['total_amount'] \
    .sum() \
    .sort_values(ascending=False)

membership  cuisine
Regular     Mexican    1072943.30
            Italian    1018424.75
Gold        Mexican    1012559.79
            Italian    1005779.05
Regular     Indian      992100.27
Gold        Indian      979312.31
            Chinese     977713.74
Regular     Chinese     952790.91
Name: total_amount, dtype: float64

In [32]:
final_df['order_date'] = pd.to_datetime(final_df['order_date'])
final_df['quarter'] = final_df['order_date'].dt.to_period('Q')

final_df.groupby('quarter')['total_amount'] \
    .sum() \
    .sort_values(ascending=False)

C:\Users\saisa\AppData\Local\Temp\ipykernel_18352\3411562792.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  final_df['order_date'] = pd.to_datetime(final_df['order_date'])

quarter
2023Q3    2037385.10
2023Q4    2018263.66
2023Q1    1993425.14
2023Q2    1945348.72
2024Q1      17201.50
Freq: Q-DEC, Name: total_amount, dtype: float64

In [33]:
gold_orders_count = final_df[
    final_df['membership'] == 'Gold'
]['order_id'].nunique()

gold_orders_count

4987

In [34]:
total_revenue_hyderabad = round(
    final_df[final_df['city'] == 'Hyderabad']['total_amount'].sum()
)

total_revenue_hyderabad

1889367

In [35]:
distinct_users = final_df['user_id'].nunique()

distinct_users

2883

In [36]:
avg_order_value_gold = round(
    final_df[final_df['membership'] == 'Gold']['total_amount'].mean(),
    2
)

avg_order_value_gold

np.float64(797.15)

In [37]:
orders_high_rating = final_df[
    final_df['rating'] >= 4.5
]['order_id'].nunique()

orders_high_rating

3374

In [38]:
gold_city_revenue = (
    final_df[final_df['membership'] == 'Gold']
    .groupby('city')['total_amount']
    .sum()
)

top_gold_city = gold_city_revenue.idxmax()
top_gold_city

'Chennai'

In [40]:
orders_top_gold_city = final_df[
    (final_df['membership'] == 'Gold') &
    (final_df['city'] == top_gold_city)
]['order_id'].nunique()

orders_top_gold_city

1337